version: "3.8"

services:
  bot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    volumes:
      - ./backend:/app
      - data:/app/shared_data # Общий volume для файла data.txt
    depends_on:
      - parser
      - selenium
    networks:
      - bot_network

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    container_name: parser_service
    restart: always
    volumes:
      - ./parser:/app
      - ./shared_data:/app/shared_data
    depends_on:
      selenium_chrome:
        condition: service_healthy
    networks:
      - bot_network

  frontend:
    build:
      context: ./registration-form
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - bot_network

  selenium_chrome:
    image: selenium/standalone-chrome
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  data: # Определение общего volume для файла data.txt
    driver: local

networks:
  bot_network:
    driver: bridge
