version: "3.8"

services:
  bot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    volumes:
      - ./backend:/app
      - data:/app/shared_data # Общий volume для файла data.txt
    depends_on:
      - parser
    networks:
      - bot_network

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    container_name: parser_service
    restart: always
    volumes:
      - ./parser:/app
      - data:/app/shared_data # Общий volume для файла data.txt
    networks:
      - bot_network

  frontend:
    build:
      context: ./registration-form
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - bot_network

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    environment:
      - SE_OPTS="--headless"
    networks:
      - bot_network

volumes:
  data: # Определение общего volume для файла data.txt
    driver: local

networks:
  bot_network:
    driver: bridge
